// Arayüz metinleri — Türkçe ve İngilizce.
//
// Yalnızca ARAYÜZ çevrilir. Durak ve turistik yer adları özel isim olduğu için
// olduğu gibi kalır; turistik özetler de Türkçe Vikipedi'den geliyor.
var DILLER = {
  tr: {
    kod: 'tr',
    dilAdi: 'Türkçe',
    digerDil: 'English',

    markaAlt: 'Aliağa – Selçuk banliyö hattı yolculuk asistanı',
    temaDegistir: 'Temayı değiştir',
    dilDegistir: 'Switch to English',

    konumBaslik: 'Konumun',
    konumAliniyor: 'Konumun alınıyor…',
    binisDuragiYap: 'Biniş durağı yap',
    yuruyerekYolTarifi: 'Yürüyerek yol tarifi',
    arabaylaYolTarifi: 'Arabayla yol tarifi',
    konumDuzelt: 'Konumum yanlış mı? Yerimi kendim gireyim',
    konumAraPlaceholder: 'Durak, mahalle veya cadde adı',
    digerDuraklar: 'Yakındaki diğer duraklar:',
    konumumuBul: 'Konumumu bul',
    konumumuYenidenBul: 'Konumumu yeniden bul',
    enYakinDurak: 'En yakın durak:',

    nereden: 'Nereden biniyorsun?',
    nereye: 'Nereye gideceksin?',
    yerDegistir: 'Biniş ve iniş duraklarını yer değiştir',
    duragaYolTarifi: 'Bu durağa yol tarifi →',

    haritaBaslik: 'Harita',
    haritaIpucu: 'Durağa tıkla · konumunu düzeltmek için işarete 2 sn basılı tut · ⊕ düğmesi konumuna döner',
    haritaKatki: 'Harita verisi © OpenStreetMap katkıcıları',
    konumaDon: 'Konumuma dön',

    basla: 'Başla',
    bitir: 'Bitir',
    sesli: 'Sesli',
    yuruyerek: 'Yürüyerek',
    arabayla: 'Arabayla',
    topluTasima: 'Toplu taşıma',
    yolTarifiniKaldir: 'Yol tarifini kaldır',
    toplamYuruyus: 'toplam yürüyüş',
    toplamSurus: 'toplam sürüş',

    siradakiTrenler: 'Sıradaki trenler',
    seferAliniyor: 'Sefer saatleri alınıyor…',
    seferYok: 'Bu durak çifti için resmî sefer verisi yayınlanmıyor (Selçuk uzantısı kapsam dışı).',
    seferYedek: 'Selçuk uzantısı için resmî sefer verisi yok; aşağıdaki saatler {durak} yönüne giden trenlerin kalkışları — biniş durağından geçen her sefer bunlar.',
    seferUlasilamiyor: 'Sefer saatlerine şu an ulaşılamıyor.',
    seferKaynak: 'kaynak: İzmir Büyükşehir Belediyesi açık veri',
    sefer: 'sefer',
    dkSonra: 'dk sonra',
    simdi: 'şimdi',
    yarin: 'yarın',

    geziBaslik: 'Gezilecek yerler',
    geziIpucu: 'Biniş ve iniş durağının çevresi · karta tıkla, yol tarifi çıksın',
    geziCevresi: 'çevresi',
    yer: 'yer',
    duraktan: 'Duraktan',
    geziKaynak: 'Metin ve görseller:',

    ozetSure: 'tahmini süre',
    ozetDurak: 'durak',
    ozetAktarma: 'aktarma noktası',
    guzergah: 'Güzergâh',
    aktarmalar: 'Yol üstündeki aktarmalar',
    binis: 'BİNİŞ',
    inis: 'İNİŞ',
    aktarma: 'AKTARMA',
    aktarmaNoktasi: 'aktarma noktası',
    kaydirarakGor: 'listeyi kaydırarak devamını gör',
    adim: 'adım',

    ozetCumle: '{binis} durağından bindin: {yon}ndeki trene binmelisin. {durak} durak sonra, yaklaşık {sure} içinde {inis} durağındasın.',
    dogruluk: 'Konum doğruluğu ±{m} m',
    dogrulukKaba: 'Konum ±{m} m doğrulukla alındı — en yakın durak şaşabilir, aşağıdan seçebilirsin.',
    elleKonum: 'Konum senin girdiğin yere göre: {etiket}',
    elleKonumSade: 'Konum senin girdiğin yere göre hesaplandı.',
    iyilestiriliyor: 'iyileştiriliyor…',
    canliTakip: 'canlı takip açık',
    yuruyusHesaplaniyor: 'Yürüyüş rotası hesaplanıyor…',
    arabaHesaplaniyor: 'Araba rotası hesaplanıyor…',
    durakSeciliyorYuruyus: 'En yakın durak yürüyüş ağına göre seçiliyor…',
    durakSeciliyorAraba: 'En yakın durak araç ağına göre seçiliyor…',
    rotaAlinamadi: 'Rota alınamadı.',
    durakBulunamadi: 'Durak bulunamadı.',
    yolaCik: 'Yola çık',
    vardin: 'Vardın.',
    yolculukBaslasin: 'Yolculuk başlasın.',
    rotadanCiktin: 'Rotadan çıktın, yeniden hesaplanıyor…',
    yeniRotaYok: 'Yeni rota alınamadı, yönlendirme durduruldu.',
    konumYokYonlendirme: 'Konum alınamadı, yönlendirme durduruldu.',
    yonlendirmeSasabilir: 'Konum ±{m} m — yönlendirme şaşabilir.',
    yerlerAraniyor: 'Yerler aranıyor…',
    sonucYok: 'Sonuç yok. Mahalle, cadde veya durak adı deneyebilirsin.',
    aramaCalismiyor: 'Yer araması şu an çalışmıyor.',
    firebaseOnbellek: 'Firebase (önbellek)',
    topluTasimaAnlat: 'İZBAN ile {durak} durağına gel. · {durak} aktarmaları: {aktarma} · ESHOT hatları: {hatlar} · Oradan {yer} için "Yürüyerek" düğmesini kullan. · Sefer saati veremiyorum: elimizde tarife verisi yok.',
    aktarmayaTarif: '{tur} aktarmasına yürüyüş yol tarifi ({mesafe})',
    duragaTarif: '{durak} durağına yürüyerek yol tarifini haritada göster',
    duragina: 'durağına',
    yonEtiketi: '{durak} yönü',
    saat: 'sa',
    dakika: 'dk',
    yolculukSecimi: 'Yolculuk seçimi',
    geziKaynakTam: 'Metin ve görseller: Wikidata · Vikipedi (CC BY-SA) · Wikimedia Commons',
    uyari: 'Uyarı:',
    uyariMetin: 'Durak sırası ve süreler tahminidir, resmî kaynak değildir. Güncel tarife için',
    veriSurumu: 'Veri sürümü:',
    kaynak: 'Kaynak:',
    yerelKopya: 'yerel kopya'
  },

  en: {
    kod: 'en',
    dilAdi: 'English',
    digerDil: 'Türkçe',

    markaAlt: 'Aliağa – Selçuk commuter line travel assistant',
    temaDegistir: 'Switch theme',
    dilDegistir: 'Türkçeye geç',

    konumBaslik: 'Your location',
    konumAliniyor: 'Getting your location…',
    binisDuragiYap: 'Set as departure',
    yuruyerekYolTarifi: 'Walking directions',
    arabaylaYolTarifi: 'Driving directions',
    konumDuzelt: 'Wrong location? Let me set it myself',
    konumAraPlaceholder: 'Station, neighbourhood or street',
    digerDuraklar: 'Other nearby stations:',
    konumumuBul: 'Find my location',
    konumumuYenidenBul: 'Find my location again',
    enYakinDurak: 'Nearest station:',

    nereden: 'Where do you board?',
    nereye: 'Where are you going?',
    yerDegistir: 'Swap departure and arrival stations',
    duragaYolTarifi: 'Directions to this station →',

    haritaBaslik: 'Map',
    haritaIpucu: 'Tap a station · hold the pin 2 s to correct your location · ⊕ returns to your location',
    haritaKatki: 'Map data © OpenStreetMap contributors',
    konumaDon: 'Back to my location',

    basla: 'Start',
    bitir: 'Finish',
    sesli: 'Voice',
    yuruyerek: 'Walking',
    arabayla: 'Driving',
    topluTasima: 'Public transport',
    yolTarifiniKaldir: 'Clear directions',
    toplamYuruyus: 'total walk',
    toplamSurus: 'total drive',

    siradakiTrenler: 'Next trains',
    seferAliniyor: 'Loading timetable…',
    seferYok: 'No official timetable is published for this pair (the Selçuk extension is not covered).',
    seferYedek: 'No official data for the Selçuk extension; the times below are departures towards {durak} — every train passing your station.',
    seferUlasilamiyor: 'Timetable is unavailable right now.',
    seferKaynak: 'source: İzmir Metropolitan Municipality open data',
    sefer: 'services',
    dkSonra: 'min from now',
    simdi: 'now',
    yarin: 'tomorrow',

    geziBaslik: 'Places to visit',
    geziIpucu: 'Around your departure and arrival stations · tap a card for directions',
    geziCevresi: 'area',
    yer: 'places',
    duraktan: 'From the station',
    geziKaynak: 'Text and images:',

    ozetSure: 'estimated time',
    ozetDurak: 'stations',
    ozetAktarma: 'interchanges',
    guzergah: 'Route',
    aktarmalar: 'Interchanges along the way',
    binis: 'BOARD',
    inis: 'EXIT',
    aktarma: 'INTERCHANGE',
    aktarmaNoktasi: 'interchange points',
    kaydirarakGor: 'scroll the list for more',
    adim: 'steps',

    ozetCumle: 'You board at {binis}: take the train towards {yon}. After {durak} stations, about {sure}, you arrive at {inis}.',
    dogruluk: 'Location accuracy ±{m} m',
    dogrulukKaba: 'Location taken with ±{m} m accuracy — the nearest station may be off, pick one below.',
    elleKonum: 'Location set by you: {etiket}',
    elleKonumSade: 'Location calculated from the point you set.',
    iyilestiriliyor: 'improving…',
    canliTakip: 'live tracking on',
    yuruyusHesaplaniyor: 'Calculating walking route…',
    arabaHesaplaniyor: 'Calculating driving route…',
    durakSeciliyorYuruyus: 'Choosing the nearest station on the walking network…',
    durakSeciliyorAraba: 'Choosing the nearest station on the driving network…',
    rotaAlinamadi: 'Could not get the route.',
    durakBulunamadi: 'No station found.',
    yolaCik: 'Set off',
    vardin: 'You have arrived.',
    yolculukBaslasin: 'Have a good trip.',
    rotadanCiktin: 'Off route, recalculating…',
    yeniRotaYok: 'Could not get a new route, guidance stopped.',
    konumYokYonlendirme: 'Location unavailable, guidance stopped.',
    yonlendirmeSasabilir: 'Location ±{m} m — guidance may be off.',
    yerlerAraniyor: 'Searching places…',
    sonucYok: 'No results. Try a neighbourhood, street or station name.',
    aramaCalismiyor: 'Place search is unavailable right now.',
    firebaseOnbellek: 'Firebase (cached)',
    topluTasimaAnlat: 'Take İZBAN to {durak}. · Interchanges at {durak}: {aktarma} · ESHOT lines: {hatlar} · From there use the "Walking" button for {yer}. · No departure times: we have no timetable data.',
    aktarmayaTarif: 'Walking directions to the {tur} interchange ({mesafe})',
    duragaTarif: 'Show walking directions to {durak} on the map',
    duragina: 'station',
    yonEtiketi: 'towards {durak}',
    saat: 'h',
    dakika: 'min',
    yolculukSecimi: 'Journey selection',
    geziKaynakTam: 'Text and images: Wikidata · Wikipedia (CC BY-SA) · Wikimedia Commons',
    uyari: 'Warning:',
    uyariMetin: 'Station order and times are estimates, not an official source. For the current timetable see',
    veriSurumu: 'Data version:',
    kaynak: 'Source:',
    yerelKopya: 'local copy'
  }
};

var DIL_ANAHTAR = 'izban.dil';

/** Seçili dil kodu: kayıt → tarayıcı dili → Türkçe. */
function dilKodunuBul() {
  try {
    var kayitli = localStorage.getItem(DIL_ANAHTAR);
    if (kayitli && DILLER[kayitli]) return kayitli;
  } catch (e) { /* özel mod */ }

  var tarayici = (navigator.language || 'tr').slice(0, 2).toLowerCase();
  return DILLER[tarayici] ? tarayici : 'tr';
}

if (typeof module !== 'undefined') {
  module.exports = { DILLER: DILLER };
}
